import type { AudioCueId, AudioCueSpec } from "../engine/audioTypes";

export const AUDIO_CUE_SPECS: Record<AudioCueId, AudioCueSpec> = {
  menu_command_loop: {
    id: "menu_command_loop",
    file: "/audio/music/menu_command_loop.mp3",
    type: "loop",
    baseVolume: 0.55,
    fadeInMs: 300,
    fadeOutMs: 450,
    priority: 10,
    loop: true,
    tags: ["menu", "ambient"],
  },
  gameplay_safe_loop: {
    id: "gameplay_safe_loop",
    file: "/audio/music/gameplay_safe_loop.mp3",
    type: "loop",
    baseVolume: 0.6,
    fadeInMs: 220,
    fadeOutMs: 350,
    priority: 20,
    loop: true,
    tags: ["gameplay", "safe"],
  },
  hazard_breach_loop: {
    id: "hazard_breach_loop",
    file: "/audio/music/hazard_breach_loop.mp3",
    type: "overlay",
    baseVolume: 0.5,
    fadeInMs: 180,
    fadeOutMs: 220,
    priority: 30,
    loop: true,
    tags: ["overlay", "hazard"],
  },
  enemy_contact_loop: {
    id: "enemy_contact_loop",
    file: "/audio/music/enemy_contact_loop.mp3",
    type: "loop",
    baseVolume: 0.68,
    fadeInMs: 180,
    fadeOutMs: 280,
    priority: 40,
    loop: true,
    tags: ["combat", "contact"],
  },
  combat_wave_loop: {
    id: "combat_wave_loop",
    file: "/audio/music/combat_wave_loop.mp3",
    type: "loop",
    baseVolume: 0.75,
    fadeInMs: 150,
    fadeOutMs: 260,
    priority: 50,
    loop: true,
    tags: ["combat", "high-intensity"],
  },
  objective_critical_layer: {
    id: "objective_critical_layer",
    file: "/audio/music/objective_critical_layer.mp3",
    type: "overlay",
    baseVolume: 0.45,
    fadeInMs: 200,
    fadeOutMs: 260,
    priority: 35,
    loop: true,
    tags: ["overlay", "objective"],
  },
  success_stinger: {
    id: "success_stinger",
    file: "/audio/stingers/success_stinger.mp3",
    type: "oneshot",
    baseVolume: 0.85,
    fadeInMs: 0,
    fadeOutMs: 120,
    priority: 100,
    loop: false,
    tags: ["result", "success"],
  },
  failure_stinger: {
    id: "failure_stinger",
    file: "/audio/stingers/failure_stinger.mp3",
    type: "oneshot",
    baseVolume: 0.85,
    fadeInMs: 0,
    fadeOutMs: 120,
    priority: 100,
    loop: false,
    tags: ["result", "failure"],
  },
};
